server:
  port: 7777
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: create
        default_schema: spring
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev
    username: daniel
    password: jesusinlove0611
  logging:
    level:
      org.jesus.shop: DEBUG
      com.zaxxer.hikari: DEBUG
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE